apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
#-------------------add reloader annotations--------------------------------------
  - patch: |-
      - op: add
        path: "/metadata/annotations"
        value: 
          configmap.reloader.stakater.com/reload: argocd-cm
    target:
      kind: Deployment

  - patch: |-
      - op: add
        path: "/metadata/annotations"
        value: 
          configmap.reloader.stakater.com/reload: argocd-cm
    target:
      kind: StatefulSet
#-------------------add monitoring annotations--------------------------------------
  - patch: |-
      - op: add
        path: "/spec/template/metadata/annotations"
        value: 
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
    target:
      kind: Deployment
      name: argocd-applicationset-controller

  - patch: |-
      - op: add
        path: "/spec/template/metadata/annotations"
        value: 
          prometheus.io/scrape: "true"
          prometheus.io/port: "8084"
    target:
      kind: Deployment
      name: argocd-repo-server

  - patch: |-
      - op: add
        path: "/spec/template/metadata/annotations"
        value: 
          prometheus.io/scrape: "true"
          prometheus.io/port: "8083"
    target:
      kind: Deployment
      name: argocd-server

  - patch: |-
      - op: add
        path: "/spec/template/metadata/annotations"
        value: 
         prometheus.io/scrape: "true"
         prometheus.io/port: "8082"
    target:
      kind: StatefulSet
      name: argocd-application-controller

#-------------------fix ERR_TOO_MANY_REDIRECTS add --insecure-----------------------
  - patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/command/-"
        value: "--insecure"
    target:
      kind: Deployment
      name: argocd-server

#-------------------delete configmaps-----------------------------------------------
#------------comments this block if you want to save your existing configmaps ------
  - path: delete-configmaps.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: delete-configmaps.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm

