apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: "/rules/0"
        value:
          apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
    target:
      kind: Role
      name: argocd-server

  - patch: |-
      - op: add
        path: "/rules/0"
        value:
          apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
    target:
      kind: ClusterRole
      name: argocd-server



